### ISSUE TITLE
How to remove "Rendered by Webcode"

### ISSUE THREAD

**Issue by fidokomik** [gerardnico/dokuwiki-plugin-webcode#9]
Is possible to remove "Rendered by Webcode ..." line at bottom of webcode rendering? Your plugin is very interesting but this advertising is disturbing :)

**Comment by gerardnico** [comment]
That's the first request of this kind that I got.

I have added it because long time ago I couldn't find how the other did it
and I spend a lot of time to discover it.

I can understand that it's may not be what you want on a UI level.

This is much more a credit thing.
I expect of every user that they will let a link that point to the website in order to give credit.
You can make it insignifiant (almost not visible) if you want.

The code is precisely on this line:
https://github.com/gerardnico/dokuwiki-plugin-webcode/blob/master/syntax/basis.php#L338

You can adapt the code. For instance, if you replace it with the below code, it should disappear. The text 'Rendered by Webcode' should disappear.
`
$poweredBy = '';
`

**Comment by tmo26** [comment]
Can this be made configurable, please?
I don't want to take away the credits for you, but the complete line (powered by, created by + jsfiddle) is just disruptive to any content displayed via this plugin.

Modifying basis.php certainly works, but is quite uncomfortable and with the next plugin update, it has to be re-done again.

**Comment by gerardnico** [comment]
No problem, great suggestion. That's true, that this is not really practical. To be sure to make no mistake, it would be great to get exactly your needs. Is it possible to get a proposition for the configuration that you want ?

**Comment by tmo26** [comment]
**Proposal:** Add a checkbox to the webcode configuration in the admin menu that let's you remove the line with powered by, created by + jsfiddle completely, either for all three items together, or separately for each item (maybe someone wants to keep the jsfiddle button).

**Comment by gerardnico** [comment]
Thanks for the proposition, I'm grateful to be able to discuss this kind of situation. 

I understand that your are asking for a configuration that removes completely the back link and I don't feel comfortable with that because of the time and effort that I have put in it.

I took the inspiration from the embedded gist from Github actually. I was not very good in Css styling that's why this is so much prominent.

**Comment by gerardnico** [comment]
I have made the bar visible on focus on the output.

You can see it in action at:
https://combostrap.com/webcode

Cheers
